spring:
  application:
    name: spring-ai-openai

  ai:
    ollama:
      base-url: http://localhost:11434/
#      chat:
#        model: llama3.2:1b

server:
  port: 9091


springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui/index.html"